### ISSUE TITLE
Corpus "somali-suugaan2" missing description properties

### ISSUE THREAD

**Issue by arildm** [spraakbanken/sb-metadata#11]
There are many resources with an empty string as description (e.g. `gdc`, `sou`, `somali-suugaan`) but the resource `somali-suugaan2` is missing it completely: [metadata/resource=somali-suugaan2](https://ws.spraakbanken.gu.se/ws/metadata/?resource=somali-suugaan2). I don't think there's any reason to differentiate between those cases, so the API would be easier to use if we handle those cases the same when building the output. (I noticed this because there were warnings in the sbwebb-cms log.)

**Comment by anne17** [comment]
Implemented a quick fix for this in 7aa699b which should ensure empty strings for descriptions and names. Also created #12 which would be a better and more general solution.
