### ISSUE TITLE
Rotate/reset log

### ISSUE THREAD

**Issue by arildm** [spraakbanken/sb-metadata#9]
`logs/update.log` is currently at 52 MB on k2

**Comment by anne17** [comment]
Sounds like a good idea. Is there any standard way of doing this?

**Comment by anne17** [comment]
I have made the logs less chatty which should decrease their size drastically. I have also implemented a naive log rotation solution in c1cd3a9 and e3beb51 which splits the log files into one per month and deletes those that are older than 6 months. Good enough I reckon!
